# Generated by Django 5.0 on 2024-02-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(null=True),
        ),
    ]
