# Generated by Django 5.0 on 2024-02-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_creditnote_company_creditnote_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
