# Generated by Django 5.0 on 2024-02-10 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_alter_creditnote_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='item',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='party',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='salesinvoice',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='grandtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='salesivoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.salesinvoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('hsn', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('tax', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billapp.creditnote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
