# Generated by Django 5.0 on 2024-02-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_remove_creditnote_item_remove_creditnote_party_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='salesivoice',
            new_name='salesinvoice',
        ),
    ]
