# Generated by Django 5.0 on 2024-02-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_rename_salesivoice_creditnote_salesinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='salesinvoice',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='salesinvoice_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='salesinvoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
