# Generated by Django 5.0 on 2024-02-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_remove_creditnote_salesinvoice_creditnote_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='salesinvoice_date',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='salesinvoice_no',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='salesinvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.salesinvoice'),
        ),
    ]
