# Generated by Django 5.0 on 2024-02-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_alter_creditnoteitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company'),
        ),
    ]
