# Generated by Django 5.0 on 2024-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_creditnoteitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='partystatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
