# Generated by Django 5.0 on 2024-03-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0018_creditnotereference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='reference_no',
        ),
    ]
